*java.nio.file.DirectoryIteratorException* *DirectoryIteratorException* Runtime 

public final class DirectoryIteratorException
  extends    |java.util.ConcurrentModificationException|

|java.nio.file.DirectoryIteratorException_Description|
|java.nio.file.DirectoryIteratorException_Fields|
|java.nio.file.DirectoryIteratorException_Constructors|
|java.nio.file.DirectoryIteratorException_Methods|

================================================================================

*java.nio.file.DirectoryIteratorException_Constructors*
|java.nio.file.DirectoryIteratorException(IOException)|Constructs an instance o

*java.nio.file.DirectoryIteratorException_Methods*
|java.nio.file.DirectoryIteratorException.getCause()|Returns the cause of this 

*java.nio.file.DirectoryIteratorException_Description*

Runtime exception thrown if an I/O error is encountered when iterating over the 
entries in a directory. The I/O error is retrieved as an 
(|java.io.IOException|) using the 
getCause()(|java.nio.file.DirectoryIteratorException|) method. 



*java.nio.file.DirectoryIteratorException(IOException)*

public DirectoryIteratorException(java.io.IOException cause)

Constructs an instance of this class. 

    cause - the {@code IOException} that caused the directory iteration to fail 

*java.nio.file.DirectoryIteratorException.getCause()*

public |java.io.IOException| getCause()

Returns the cause of this exception. 



    Returns: 


